on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: golangci/golangci-lint-action@v3.1.0

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - uses: goreleaser/goreleaser-action@v2.8.0
      with:
        args: check

    - uses: goreleaser/goreleaser-action@v2.8.0
      with:
        args: release --snapshot --rm-dist
